version: '3'

services:
  elasticsearch:
    container_name: es7
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      - node.name=es7
      - cluster.name=es7-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    volumes:
#      - D:\Personal-KS\Project\esdata:/usr/share/elasticsearch/data
    ports:
      - "9300:9300"
      - "9200:9200"