version: '3'

services:
  elasticsearch:
    container_name: es7
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - node.name=es7
      - cluster.name=es7-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.audit.enabled=true
      - ELASTIC_PASSWORD=admin123
    volumes:
      - I:\Project\elasticsearch\esData:/usr/share/elasticsearch/data
    ports:
      - "9300:9300"
      - "9200:9200"
    networks:
      - elastic-kibana

  kibana:
    container_name: kibana7
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es7:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=admin123
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic-kibana

networks:
  elastic-kibana:
    driver: bridge
